// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  production: true,
  version: env.npm_package_version,
  // basePath : 'https://alindrelays.com/',
  // serverUrl: 'https://alindrelays.com/',
  // basePath : 'http://localhost:8080/',
  //serverUrl: 'http://localhost:8080/',
  //Local
   // basePath : 'http://localhost:8080/',
  // serverUrl: 'http://localhost:8080/',
    //New Server
  basePath : 'http://97.74.85.211:8080/',
  serverUrl: 'http://97.74.85.211:8080/',
  
  defaultLanguage: 'en-US',
  supportedLanguages: [
    'en-US',
    'fr-FR'
  ]
};
