// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  production: true,
  version: env.npm_package_version,
 // basePath : 'http://148.66.135.25:10002/',
  //serverUrl: 'http://148.66.135.25:10002/',
basePath : 'http://148.66.135.25:10002/',
serverUrl: 'http://148.66.135.25:10002/',
  defaultLanguage: 'en-US',
  supportedLanguages: [
    'en-US',
    'fr-FR'
  ]
};
